# Generated by Django 4.2.14 on 2026-01-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Discord webhook URL', max_length=500)),
                ('name', models.CharField(help_text='User-friendly name for this webhook', max_length=100)),
                ('enabled', models.BooleanField(default=True, help_text='Enable/disable this webhook')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Discord Webhook',
                'verbose_name_plural': 'Discord Webhooks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WebhookSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssh_logins_enabled', models.BooleanField(default=False, help_text='Enable SSH login notifications')),
                ('security_warnings_enabled', models.BooleanField(default=False, help_text='Enable security warning notifications')),
                ('server_usage_enabled', models.BooleanField(default=False, help_text='Enable server usage notifications')),
                ('server_usage_cpu', models.BooleanField(default=True, help_text='Include CPU metrics in server usage notifications')),
                ('server_usage_memory', models.BooleanField(default=True, help_text='Include memory metrics in server usage notifications')),
                ('server_usage_disk', models.BooleanField(default=True, help_text='Include disk metrics in server usage notifications')),
                ('server_usage_network', models.BooleanField(default=False, help_text='Include network metrics in server usage notifications')),
                ('server_usage_threshold_mode', models.BooleanField(default=True, help_text='Threshold-based notifications (only notify when thresholds exceeded)')),
                ('cpu_threshold', models.IntegerField(default=80, help_text='CPU threshold percentage (0-100)')),
                ('memory_threshold', models.IntegerField(default=80, help_text='Memory threshold percentage (0-100)')),
                ('disk_threshold', models.IntegerField(default=85, help_text='Disk usage threshold percentage (0-100)')),
                ('check_interval', models.IntegerField(default=5, help_text='Server usage check interval in minutes (minimum 1)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Webhook Settings',
                'verbose_name_plural': 'Webhook Settings',
            },
        ),
    ]
