# Generated by Django 4.2.14 on 2026-02-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csp_enabled', models.BooleanField(default=True, help_text='Enable/disable CSP globally')),
                ('apply_to_plugins', models.BooleanField(default=True, help_text='Apply CSP to plugin routes')),
                ('apply_to_core', models.BooleanField(default=True, help_text='Apply CSP to core CyberPanel pages')),
                ('plugin_settings', models.TextField(default='{}', help_text='JSON object storing per-plugin CSP settings')),
                ('allow_google_analytics', models.BooleanField(default=True, help_text='Allow Google Analytics')),
                ('allow_google_tag_manager', models.BooleanField(default=True, help_text='Allow Google Tag Manager')),
                ('allow_discord_auth', models.BooleanField(default=True, help_text='Allow Discord Auth resources')),
                ('allow_angularjs', models.BooleanField(default=True, help_text='Allow AngularJS from code.angularjs.org')),
                ('allow_jquery', models.BooleanField(default=True, help_text='Allow jQuery from code.jquery.com')),
                ('allow_cdn_resources', models.BooleanField(default=True, help_text='Allow CDN resources (jsDelivr, Cloudflare, etc.)')),
                ('permissive_plugin_csp', models.BooleanField(default=True, help_text='Use permissive CSP for plugins (allows more resources)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CSP Configuration',
                'verbose_name_plural': 'CSP Configurations',
            },
        ),
    ]
