# Generated by Django 4.2.14 on 2026-02-02 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContaboConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_client_id', models.CharField(blank=True, help_text='Contabo API Client ID', max_length=255)),
                ('api_client_secret', models.CharField(blank=True, help_text='Contabo API Client Secret', max_length=255)),
                ('api_key', models.CharField(blank=True, help_text='Contabo API Key', max_length=255)),
                ('api_secret', models.CharField(blank=True, help_text='Contabo API Secret', max_length=255)),
                ('api_base_url', models.URLField(default='https://api.contabo.com/v1', help_text='Contabo API Base URL')),
                ('auto_backup_enabled', models.BooleanField(default=True, help_text='Enable/disable automatic snapshots globally. When disabled, all schedules are paused.')),
                ('max_snapshots_per_vps', models.IntegerField(default=10, help_text='Maximum number of snapshots to keep per VPS (based on your Contabo plan limit). Set to 0 for unlimited (not recommended).')),
                ('payment_method', models.CharField(choices=[('patreon', 'Patreon Subscription'), ('paypal', 'PayPal Payment'), ('both', 'Check Both (Patreon or PayPal)')], default='both', help_text="Choose which payment method to use for verification. 'Check Both' will grant access if either method is valid.", max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contabo Configuration',
                'verbose_name_plural': 'Contabo Configurations',
            },
        ),
        migrations.CreateModel(
            name='SnapshotSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Schedule name', max_length=100)),
                ('vps_id', models.CharField(help_text='Contabo VPS Instance ID', max_length=50)),
                ('schedule_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom Cron')], default='daily', max_length=20)),
                ('cron_expression', models.CharField(blank=True, help_text="Custom cron expression (e.g., '0 2 * * *' for daily at 2 AM)", max_length=100)),
                ('snapshot_name_prefix', models.CharField(default='auto-snapshot', help_text="Prefix for snapshot names (e.g., 'auto-snapshot' will create 'auto-snapshot-2025-01-15-10-30')", max_length=50)),
                ('include_ram', models.BooleanField(default=False, help_text='Include RAM state in snapshot')),
                ('description_template', models.CharField(default='Auto snapshot created on {date}', help_text='Description template (use {date} for date placeholder)', max_length=255)),
                ('retention_count', models.IntegerField(default=5, help_text='Number of snapshots to keep for this schedule (0 = keep all, but respect global max_snapshots_per_vps limit)')),
                ('auto_delete_old', models.BooleanField(default=True, help_text='Automatically delete old snapshots when retention limit is reached')),
                ('enabled', models.BooleanField(default=True, help_text='Enable/disable this schedule')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run', models.DateTimeField(blank=True, help_text='Last time this schedule ran', null=True)),
                ('next_run', models.DateTimeField(blank=True, help_text='Next scheduled run time', null=True)),
            ],
            options={
                'verbose_name': 'Snapshot Schedule',
                'verbose_name_plural': 'Snapshot Schedules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SnapshotHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vps_id', models.CharField(help_text='Contabo VPS Instance ID', max_length=50)),
                ('snapshot_name', models.CharField(help_text='Snapshot name', max_length=255)),
                ('snapshot_id', models.CharField(blank=True, help_text='Contabo snapshot ID (if available)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Snapshot description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('creating', 'Creating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if snapshot failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('schedule', models.ForeignKey(blank=True, help_text='Schedule that created this snapshot (null if manual)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contaboAutoSnapshot.snapshotschedule')),
            ],
            options={
                'verbose_name': 'Snapshot History',
                'verbose_name_plural': 'Snapshot History',
                'ordering': ['-created_at'],
            },
        ),
    ]
