# Generated by Django 4.2.14 on 2026-02-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contaboAutoSnapshot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaboconfig',
            name='activation_key',
            field=models.CharField(blank=True, default='', help_text='Validated activation key - grants access without re-entering on each page load', max_length=64),
        ),
    ]
