# Generated by Django 4.2.14 on 2026-02-02 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contaboAutoSnapshot', '0002_contaboconfig_activation_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaboconfig',
            name='api_max_snapshots_from_plan',
            field=models.IntegerField(blank=True, help_text='Max snapshots from Contabo plan (fetched when API tested). User cannot set higher.', null=True),
        ),
        migrations.AddField(
            model_name='contaboconfig',
            name='api_tested',
            field=models.BooleanField(default=False, help_text='True after successful Test Connection'),
        ),
        migrations.AlterField(
            model_name='contaboconfig',
            name='max_snapshots_per_vps',
            field=models.IntegerField(default=1, help_text='Maximum snapshots per VPS (set from Contabo plan after API test). Cannot exceed your plan limit.'),
        ),
    ]
