#!/usr/local/CyberCP/bin/python
RESET = '\033[0;0m'
BLUE = "\033[0;34m"
GREEN = "\033[0;32m"
print(BLUE + "Limited phpMyAdmin: post-install" + RESET)
print(GREEN + "Migrations run by CyberPanel plugin installer when enable_migrations is present." + RESET)
